module.exports = {
  name: 'Admin System',
  prefix: 'system',
  footerText: 'TROY ADMIN SYSTEM  © 2017 ',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  // activeUrl: 'http://10.0.40.90:8081',
  activeUrl: 'http://10.0.40.47:8081',
  baseURL: '/system',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7000'],
  openPages: ['/login'],
  apiPrefix: '/system',
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/dashboard',
    mycity: 'http://www.zuimeitianqi.com/zuimei/myCity',
    myWeather: 'http://www.zuimeitianqi.com/zuimei/queryWeather',
  },
}
